[project]
name = "compliance-report"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "apache-airflow==3.0.6",
    "apache-airflow-providers-snowflake",
    "apache-airflow-providers-common-sql",
    "pandas",
]
